import type { ConversationItem } from '@core/domain/conversation';

/**
 * Input type for appending a new conversation item.
 * Omits fields that are set by the service or repo:
 * - id: generated by the service
 * - conversationId: provided as a separate parameter
 * - createdAt, updatedAt: set by the repo
 *
 * Note: turnIndex IS included - caller provides it.
 */
export type AppendItemData = Omit<
  ConversationItem,
  'id' | 'conversationId' | 'createdAt' | 'updatedAt'
>;
