import type {
  ConversationItem,
  MessageItem,
  AgentItem,
} from "@core/domain/conversation";

/**
 * Input type for appending a new conversation item.
 * Omits fields that are set by the service or repo:
 * - id: generated by the service
 * - conversationId: provided as a separate parameter
 * - createdAt, updatedAt: set by the repo
 *
 * Note: turnIndex IS included - caller provides it.
 *
 * Uses distributive omit to properly handle discriminated union types.
 */
export type AppendItemData =
  | Omit<MessageItem, "id" | "conversationId" | "createdAt" | "updatedAt">
  | Omit<AgentItem, "id" | "conversationId" | "createdAt" | "updatedAt">;
