import zod from 'zod';

export type GeneratedFile = zod.infer<typeof generatedFileSchema>;

export const generatedFileSchema = zod
  .strictObject({
    base64: zod.string().describe('File as a base64 encoded string.'),
    uint8Array: zod.any().describe('File as a Uint8Array.'),
    mediaType: zod.string().describe('The IANA media type of the file.'),
  })
  .describe('A file generated by the model.');
