import zod from 'zod';

export type GeneratedFile = zod.infer<typeof generatedFileSchema>;

export const generatedFileSchema = zod
  .strictObject({
    data: zod.string().describe('Base64 encoded file data.'),
    mediaType: zod.string().describe('IANA media type of the file.'),
  })
  .describe('A file generated by the model.');
