import zod from 'zod';

export type GeneratedFile = zod.infer<typeof generatedFileSchema>;

export const generatedFileSchema = zod
  .strictObject({
    uint8Array: zod
      .instanceof(Uint8Array<SharedArrayBuffer | ArrayBuffer>)
      .describe('File as a Uint8Array.'),
    mediaType: zod.string().describe('The IANA media type of the file.'),
  })
  .describe('A file generated by the model.');
