import {
  type AgentRunOptions,
  type AgentRunState,
  type AgentState,
  DEFAULT_AGENT_TIMEOUT,
} from '@backend/agents/domain';
import type { Context } from '@backend/infrastructure/context/Context';
import type { ILogger } from '@backend/infrastructure/logger/Logger';
import type { IStorageService } from '@backend/storage/domain/StorageService';
import type {
  AgentManifest,
  AgentRequest,
  AgentRunId,
  AgentTool,
} from '@core/domain/agents';
import type { AppError } from '@core/errors/AppError';
import { err, ok, type Result } from 'neverthrow';
import { buildInitialMessages } from '../messages/buildInitialMessages';
import { deserializeMessages } from '../serialization/deserializeMessages';

/**
 * Initializes a fresh agent run state.
 *
 * Pure function that assembles initial state from manifest and request.
 * Tools are passed in (already built by caller).
 *
 * @param stateId - The state ID for this run (generated by prepareFromRequest)
 */
export function initializeAgentRun(
  stateId: AgentRunId,
  manifest: AgentManifest,
  request: AgentRequest,
  tools: AgentTool[],
  toolsMap: Map<string, AgentTool>,
  options?: AgentRunOptions,
): AgentRunState {
  const startTime = Date.now();
  const timeoutMs =
    manifest.config.timeout ?? options?.agentTimeout ?? DEFAULT_AGENT_TIMEOUT;
  const messages = buildInitialMessages(manifest, request);

  return {
    runId: stateId,
    startTime,
    timeoutMs,
    tools,
    toolsMap,
    messages,
    steps: [],
    stepNumber: 0,
    outputValidationRetries: 0,
  };
}

/**
 * Restores agent run state from saved state (for continueAgent).
 *
 * Tools are passed in (already built by caller).
 * Deserializes messages (refreshes binary content URLs).
 * Uses savedState.id as runId since we're continuing an existing state.
 */
export async function restoreAgentRun(
  ctx: Context,
  manifest: AgentManifest,
  savedState: AgentState,
  tools: AgentTool[],
  toolsMap: Map<string, AgentTool>,
  deps: { storageService: IStorageService; logger: ILogger },
): Promise<Result<AgentRunState, AppError>> {
  const startTime = Date.now();
  const timeoutMs = manifest.config.timeout ?? DEFAULT_AGENT_TIMEOUT;

  // Deserialize messages (refresh signed URLs for binary content)
  const messagesResult = await deserializeMessages(ctx, savedState.messages, {
    storageService: deps.storageService,
    logger: deps.logger,
  });

  if (messagesResult.isErr()) {
    return err(messagesResult.error);
  }

  return ok({
    runId: savedState.id, // Use existing state ID
    startTime,
    timeoutMs,
    tools,
    toolsMap,
    messages: messagesResult.value,
    steps: savedState.steps,
    stepNumber: savedState.currentStepNumber,
    outputValidationRetries: 0, // Reset on continue
  });
}
