import type { AgentManifest } from '@backend/agents/domain';
import {
  type AgentRunOptions,
  type AgentRunState,
  DEFAULT_AGENT_TIMEOUT,
} from '@backend/agents/domain';
import type { AgentRequest, AgentRunId, AgentTool } from '@core/domain/agents';
import { buildInitialMessages } from '../messages/buildInitialMessages';

/**
 * Initializes a fresh agent run state.
 *
 * Pure function that assembles initial state from manifest and request.
 * Tools are passed in (already built by caller).
 *
 * @param stateId - The state ID for this run (generated by prepareFromRequest)
 */
export function initializeAgentRun(
  stateId: AgentRunId,
  manifest: AgentManifest,
  request: AgentRequest,
  tools: AgentTool[],
  toolsMap: Map<string, AgentTool>,
  options?: AgentRunOptions,
): AgentRunState {
  const startTime = Date.now();
  const timeoutMs =
    manifest.config.timeout ?? options?.agentTimeout ?? DEFAULT_AGENT_TIMEOUT;
  const messages = buildInitialMessages(manifest, request);

  return {
    runId: stateId,
    startTime,
    timeoutMs,
    tools,
    toolsMap,
    messages,
    steps: [],
    stepNumber: 0,
    outputValidationRetries: 0,
  };
}
