name: Update Status Check
description: Updates a status check for the PR

inputs:
  check_id:
    description: "The ID of the status check"
    required: true
  outcome:
    description: "The outcome of the status check"
    required: true
  token:
    description: "The GitHub token to use for authentication"
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
